name: Our CI

on:
  pull_request:
  push:
    branches:
      - main
      - other-brach
  workflow_dispath:

jobs:
  test::
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"